openapi: 3.0.3
info:
  title: PSS Request API
  description: A request for PSS (Prescriber Support System) results.
  version: 1.0.0
paths:
  /PSSRequest.schema.json:
    get:
      summary: JSON Schema definition for the Logical Model PSSRequest
      description: This endpoint serves the JSON Schema definition for the Logical
        Model PSSRequest.
      responses:
        '200':
          description: The JSON Schema for PSSRequest
          content:
            application/schema+json:
              schema:
                $ref: ./PSSRequest.schema.json
components:
  schemas:
    PSSRequest:
      $schema: https://json-schema.org/draft/2020-12/schema
      $id: https://www.ehealth.fgov.be/standards/fhir/pss/StructureDefinition/PSSRequest.schema.json
      title: PSS Request
      description: A request for PSS (Prescriber Support System) results.
      type: object
      properties:
        recordedDate:
          type: string
          format: date
          description: Date on which the information was recorded
        pssidentifier:
          type: object
          description: Identifier of the exchange session
        examination:
          type: object
          description: The ID of the examination the prescriber wants to prescribe
        indication:
          type: array
          items:
            type: object
          minItems: 1
          description: Indication that triggers the PSS request, from structured list
            or free text
        supportingInfo:
          type: object
          description: Information useful for PSS proposals
        id:
          type: object
          description: Unique id for the element within a resource (for internal references).
            This may be any string value that does not contain spaces.
        modifierExtension:
          type: array
          items:
            type: object
            description: FHIR Extension
          description: 'May be used to represent additional information that is not
            part of the basic definition of the element and that modifies the understanding
            of the element in which it is contained and/or the understanding of the
            containing element''s descendants. Usually modifier elements provide negation
            or qualification. To make the use of extensions safe and manageable, there
            is a strict set of governance applied to the definition and use of extensions.
            Though any implementer can define an extension, there is a set of requirements
            that SHALL be met as part of the definition of the extension. Applications
            processing a resource are required to check for modifier extensions.


            Modifier extensions SHALL NOT change the meaning of any elements on Resource
            or DomainResource (including cannot change the meaning of modifierExtension
            itself).'
        patientAge:
          type: object
          description: Age of the patient
        patientGender:
          type: object
          description: Gender of the patient
      required:
      - recordedDate
      - pssidentifier
      - indication
      - supportingInfo
      - patientAge
      - patientGender
      fhir:logicalModel: https://www.ehealth.fgov.be/standards/fhir/pss/StructureDefinition/PSSRequest
      fhir:parent: http://hl7.org/fhir/StructureDefinition/Base
